### ISSUE TITLE
Un peu trop long ?

### ISSUE THREAD

**Issue by guilhem** [onestlatech/onestlatech.github.io#1195]
Actuellement, il me semble, que le message est beaucoup trop long et peu clair.

Il aborde beaucoup trop de sujets (pertinents) mais ne se focalise pas sur l'essentiel : la reforme des retraites.

Serait-il possible de condenser le message (cela peut être via un `TL;DR`) ?

**Comment by supertanuki** [comment]
L'appel a été signé par plus de 1200 personnes. Pas possible de le modifier.
Proposer un résumé risque de dénaturer l'appel.
Il y a quelques articles de presse qui "tente" de résumer l'appel.

**Comment by guilhem** [comment]
Alors c'est peut-être un biai de mon métier... mais un "contrat' sans version... ce n'est pas un "contrat" prêt pour la prod.

Donc le document actuel est une version 1.0, très bien, ça ne dois pas être une excuse pour ne pas s'améliorer et proposer de nouvelles révisions (amélioration continue etc).

**Comment by guilhem** [comment]
De plus, et c'est peut-être un biais de secteur, mais tous les retours que j'ai sont :
![image](https://user-images.githubusercontent.com/486876/70915014-6476cd00-2019-11ea-94ca-254e08865e3a.png)
![image](https://user-images.githubusercontent.com/486876/70915035-6c367180-2019-11ea-963e-9efaa70ca3a8.png)

Après on peut ne pas entendre et se dire que c'est "normal". C'est un choix et un parti pris que je peux entendre s'il est explicite (et cela conditionne bien sûr la prise de décision).

**Comment by supertanuki** [comment]
@guilhem comment tu fais resigner des gens sur des nouvelles versions ?

Si 900 mots n'ont pas effrayé 1200+ signataires et que ça bloque quelques uns qui trouve ça trop long, tant pis.

**Comment by supertanuki** [comment]
@guilhem tu peux proposer un texte court sous forme de publication : https://onestla.tech/publications/
Rejoins le discord pour en parler à toutes et tous.

**Comment by guilhem** [comment]
> @guilhem comment tu fais resigner des gens sur des nouvelles versions ?

Le mythe de l'uniformité est juste désuète.
Ils ont signé une version de la déclaration. Cool.
Si tu as une autre version, tu auras d'autres gens qui signeront pour la seconde.

Juste comme exemple : Creative Common, GPL… Tous ont des versions qui vivent en parallèle.

> Si 900 mots n'ont pas effrayé 1200+ signataires et que ça bloque quelques uns qui trouve ça trop long, tant pis.

1200 personnes c'est cool, 10k, 100k c'est encore mieux.
Pour le moment, désolé, mais je ne peux pas signer en l'état un texte peu clair qui peut servir de base à un discours que je ne peux cautionner.
