### ISSUE TITLE
Améliorer l'aperçu sur les réseaux sociaux

### ISSUE THREAD

**Issue by antoinerousseau** [onestlatech/onestlatech.github.io#1387]
Il faudrait améliorer/changer/ajouter les tags OpenGraph.

Actuellement :
<img width="514" alt="Capture d'écran 2019-12-17 20 52 49" src="https://user-images.githubusercontent.com/160279/71029268-57d4a080-210f-11ea-9a94-f422e30d119c.png">

**Comment by dunglas** [comment]
PR bienvenue :)

**Comment by antoinerousseau** [comment]
@dunglas voilà :)
