### ISSUE TITLE
Signer l'appel

### ISSUE THREAD

**Issue by jeanbaptistemora** [onestlatech/onestlatech.github.io#1865]
[Jean-Baptiste Mora](https://moramora.fr), développeur

**Comment by dunglas** [comment]
On comprend ta frustration. Le dépôt est actuellement en maintenance car les dépendances du scripts sont obsolètes.

Le collectif est une association de fait gérée par des bénévoles sur leur temps libre. Bien qu'un DPO ne soit pas obligatoire ici, nous prenons le RGPD au sérieux. Nous allons faire au mieux pour traiter ta demande dans les meilleurs délais (le délai légal étant d'un mois, extensible à trois en cas de complexité technique, ce qui est notre cas ici).

Si tu as des compétences techniques pour nous aider à réparer les scripts ou structurer le collectif (loi 1901, mentions légales), tu es le bienvenu, on manque de bras !

**Comment by dunglas** [comment]
Voilà, ta signature est retirée.

J'en ai profité pour réparer le Hugo et ajouter tous les nouveaux signataires.
