### ISSUE TITLE
Mode de contribution au dépôt

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#247]
Pourquoi ajouter les noms à la fin de la liste plutôt que de continuer dans l'ordre alphabétique ?

J'ai bien vu qu'il y a eu depuis hier soir de grosses difficultés de contributions *(suppression par erreurs de noms, non résolutions de conflits, etc.)*, mais je ne crois pas qu'ajouter les noms à la fin  de la liste permette de les éviter. 
Préserver l'ordre alphabétique va permettre de limiter au minimum les risques de conflits, là ou l'insertion en fin de liste va systématiquement provoquer des conflits entre contributeurs.

Je ne peux que suggérer, plutôt que de traiter manuellement tous les ajouts, de recommencer à valider les [_pull-request_](https://github.com/onestlatech/onestlatech.github.io/pulls) qui sont correctes *(en vérifiant systématiquement que leur contenu dans l'onglet  **Files changed** n'est bien qu'un ajout et non une suppression)*.

Dans un second temps, les [_pull-request_](https://github.com/onestlatech/onestlatech.github.io/pulls) problématiques _(supprimant des lignes par erreur, ou commits en conflit)_ ne peuvent, elles, qu'être traitées manuellement.

---

*Ce ne sont là que des suggestions par rapport à ce qu'il me semble avoir compris de la situation du dépôt mais je comprendrais très bien que, n'ayant qu'une vue partielle, je puisse me tromper.
Si je peux être utile en faisant avancer les choses, je suis ouvert aux échanges.*

**Comment by supertanuki** [comment]
La gestion actuelle pose des soucies de conflits. Il y a actuellement 1 à 2 signatures à la minute, on s'attendait sans doute pas à un tel succès (et les problèmes qui vont avec). On est en train de réfléchir à d'autres moyens.
Merci pour les suggestions

**Comment by julienc91** [comment]
+1
Même constat que @mabhub par expérience (un gros fichier de constantes où chaque développeur rajoutait à l'arrache sa nouvelle constante en fin de liste). L'ajout en fin de fichier sur un fichier constamment modifié va quasi-systématiquement entraîner un conflit de merge. Alors qu'un ajout par ordre alphabétique n'aura de conflit que si deux lignes adjacentes auront été modifiées.

**Comment by pocky** [comment]
Sous entendu que les gens mettent bien leur nom dans l'ordre alphabétique et ne se mettent pas dans la tête de proposer des changements de l'ordre en plus dans leur PR (c'est ce qui est arrivé hier et du coup voila :p)

**Comment by mabhub** [comment]
**AMHA** il est urgent dans un premier temps de changer le texte pour ne plus demander d'ajouter les noms en fin de liste, mais bien par **ordre alphabétique**.

Cela permettrait de rendre la majorité des nouvelles _pull requests_ valides, et donc de les fusionner en un clic *(lorsqu'elles sont valides, après vérif)*. 

*(Actuellement, tout le monde ajoute à la fin : la fusion n'est possible que manuellement)*

**Comment by supertanuki** [comment]
Pour info : https://github.com/onestlatech/onestlatech.github.io/pull/134

On tente de passer par les issues et on copie/colle directement sur master (admin)

**Comment by ronane** [comment]
J'ai pas de recommandation particulière sur l'issue mais bon courage pour la gestion des signatures en tout cas. 
Merci pour votre appel, ça fait du bien de voir que dans la tech il y a aussi du monde qui se bouge alors que globalement le domaine est un peu privilégié par rapport à d'autres secteurs d'activité.

**Comment by dunglas** [comment]
@pocky et moi avons ajouté un script Ruby qui récupère les dernières signatures, ferme les tickets associés, ajoute les nouvelles signatures au fichier, les déduplique et les classe par ordre alphabétique. Je pense que ça aidera suffisamment : https://github.com/onestlatech/onestlatech.github.io/blob/content/list.rb
