### ISSUE TITLE
Outils pour facilement mettre son site en grève?

### ISSUE THREAD

**Issue by Einenlum** [onestlatech/onestlatech.github.io#307]
Dans le texte, on parle d’afficher son soutien à la grève sur nos sites respectifs.

Certains outils tels que [strike-js](https://github.com/thibault/strike-js) permettent facilement de mettre temporairement son site en grève.

Peut-être qu’ajouter un lien vers ce type d’outils pourrait aider certains devs à rejoindre le mouvement (sans strike-js, je ne sais pas si j’aurais eu le temps et l’énergie de modifier le layout de mon site pour le mettre en grève).

**Comment by dunglas** [comment]
Oui ça serait bien ! Peut-être ajouter une nouvelle page dédiée à ça ?
