### ISSUE TITLE
Update https://blogs.mediapart.fr/onestlatech/blog/101219/appel-des-travailleuses-et-travailleurs-du-numerique-pour-une-autre-reforme-des-retraites?xtor=CS3-67

### ISSUE THREAD

**Issue by glennie** [onestlatech/onestlatech.github.io#501]
Hi,
https://blogs.mediapart.fr/onestlatech/blog/101219/appel-des-travailleuses-et-travailleurs-du-numerique-pour-une-autre-reforme-des-retraites?xtor=CS3-67 is still asking to create PR in order to add one's name.
Please update it stating an issue should be used instead or MR.
Kind regards,

**Comment by dunglas** [comment]
Fixed, thanks!
