### ISSUE TITLE
Ajouter quelques labels d'issues

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#529]
Pour améliorer la lisibilité de la liste d'issues, il pourrait être pertinent de [créer à minima un label "signature"](https://github.com/onestlatech/onestlatech.github.io/issues/labels) à ajouter au [template d'issue](https://github.com/onestlatech/onestlatech.github.io/blob/content/.github/ISSUE_TEMPLATE/signature.md).

Il serait ainsi aisé d'afficher [uniquement les demandes de signatures](https://github.com/onestlatech/onestlatech.github.io/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Asignature), ou bien d'afficher [*tout sauf* les demandes de signature](https://github.com/onestlatech/onestlatech.github.io/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Asignature).

**Comment by pocky** [comment]
Très bonne idée qui m'a permise au passage de faire un petit script ruby pour nous faciliter la vie :)
