### ISSUE TITLE
Rediriger http://www.onestla.tech/ vers https://onestla.tech/

### ISSUE THREAD

**Issue by pierreroth64** [onestlatech/onestlatech.github.io#542]
Toutes les personnes à qui j'ai dit : _"va voir sur onestla [point] tech"_ sont allées sur `http://www.onestla.tech/` et plouf, le trou 😥 
Si possible, rediriger `http://www.onestla.tech/` vers `https://onestla.tech/`

**Comment by dunglas** [comment]
C'est fait. Ca devrait être actif d'ici quelques heures.

**Comment by pierreroth64** [comment]
🤔 ... fix il y a 11h et le problème est toujours là mais l'erreur a changé: ce n'est plus une erreur DNS mais un contenu vide...
**Sur firefox:**
<img width="873" alt="error-firefox" src="https://user-images.githubusercontent.com/4201248/70616360-8a156800-1c0e-11ea-9826-426d6d38ef63.png">
**Sur chrome:**
<img width="722" alt="error-chrome" src="https://user-images.githubusercontent.com/4201248/70616363-8aadfe80-1c0e-11ea-894a-87e2653b7a7d.png">

**Comment by pierreroth64** [comment]
Faudrait réouvrir l'issue.... Merci !

**Comment by dunglas** [comment]
On dirait que le système de web forwarding de Gandi ne marche pas... Je regarde ça dès que possible. Au pire je migrerai les DNS sur CloudFlare.

**Comment by dunglas** [comment]
J'ai basculer les DNS chez Cloudflare et j'ai créer une règle de direction. Il n y a plus qu'à attendre que ça se propage, en espérant que ça marche cette fois.
