### ISSUE TITLE
Nettoyer les branches fusionnées

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#690]
Il y a un grand nombre _(plus d'une 15aine)_ de branches qui ont été fusionnées mais qui encombrent encore le dépôt : https://github.com/onestlatech/onestlatech.github.io/branches/all

Il serait pertinent de les supprimer : 
![image](https://user-images.githubusercontent.com/1846633/70615751-4837f200-1c0d-11ea-838e-83444dcfd3ab.png)

**Comment by dunglas** [comment]
fait ^^
