### ISSUE TITLE
Le script d'import de signature ajoute des artefacts

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#760]
Je pense que cela vient du script d'import des signatures, je n'en suis pas certain, mais le fait est que beaucoup de nouvelles signatures se retrouvent avec en fin de ligne
- soit ` ` *(espace surnuméraire)*, 
- soit ` - ` *(espace, trait d'union, espace)*

Le script de signature peut-il évoluer pour tenter d'éviter ces écueils ?

On peut en voir les corrections dans cc4f1912dd81096af7aca834e7e68fb0d83fbe1b, 77b018a6a7647c2b057662227abe31e8e3f203e1, et dans #757

**Comment by pocky** [comment]
Je me suis fait exactement la même remarque suite à ta PR. On regarde ça ce soir :)

**Comment by dunglas** [comment]
En fait le script plante encore quand les gens ne respectent le template d'issue GitHub, dans ce cas j'importe à la main à parti des logs du script et il reste quelques erreurs de ce type.

**Comment by dunglas** [comment]
Ca devrait être réglé dans la dernière version. Je ferme pour le moment.
