### ISSUE TITLE
Commentaires de signature tendancieux

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#764]
Certains ajouts sont parfois fait à la suite des mentions courantes _(poste / statut / structure)_.
Ces ajouts peuvent être tendancieux, partisans, flirter avec le publicitaire ou simplement humoristique.

**Mon avis personnel** est qu'il ne faudrait pas permettre ces mentions supplémentaire, car elles ajoutent à la page des messages qui ne sont pas nécessairement portés ou acceptés par l'ensemble des signataires, et donc nuisent au message initial ; même s'il peuvent partir d'une bonne intention ou sembler aller dans le sens de l'appel principal.

On trouve par exemple actuellement :
- "… alternative à l'uberisation"
- "… (chat-)touilleur digital (mais néanmoins agitateur numérique)"
- "… je ne suis pas ingénieur, je suis infirmier,…"
- "… Déjà en grève et en manif le 5, je serais des prochaines mobilisations... Marre de ces pseudo réforme qui sont surtout une privatisation du bien commun !"
- "… chien du TAO (travail assisté par ordinateur)"
- "… 100% Agree"

Je propose de retirer ces mentions qui vont au delà de la signature.

**Comment by dunglas** [comment]
👍. On a automatisé le processus de signature du coup on ne retouche pas chaque intitulé. N’hésite pas à ouvrir une PR.

**Comment by mabhub** [comment]
Oui oui j'imaginais bien que ce *nettoyage* devrait-être manuel, mais je voulais avoir un avis sr le principe avant de proposer une PR.
