### ISSUE TITLE
Ajouter un menu d'ancres (a11y)

### ISSUE THREAD

**Issue by mabhub** [onestlatech/onestlatech.github.io#887]
Afin d'ajouter une possibilité de naviguer au clavier dans la page, il pourrait être utile d'ajouter un menu d'ancres. D'autant qu'avec la liste des signatures, l'accès aux parties suivantes est contraint à un _long_ défilement qui, pour certain, peut-être compliqué.

C'est en somme une table des matières permettant d'avoir des liens qui pointent vers les différentes parties.

Ce menu peut-être visible. Mais il peut également être invisible par défaut, et ne s'afficher que lors d'une navigation au clavier, lorsque chaque élément de ce menu dispose du `:focus` *(le plus souvent via la touche <kbd>tab</kbd>)*.

Par exemple : 
- aller sur https://www.opquast.com/
- appuyer <kbd>tab</kbd> : le premier élément visible prend le focus.
- appuyer 3 fois de plus sur <kbd>tab</kbd> on voit apparaître un élément de menu, visible uniquement dans le cadre de la navigation au clavier, qui permet d'envoyer *(en faisant <kbd>entrée</kbd>)* le scroll et le focus directement vers la partir concerner.

On pourrait imaginer le vocabulaire suivant : 
- Lire l'appel
- Comment signer
- Liste des personnes signataires
- Liste des organisations signataires
- À propos de cette pétition

Il faut avoir en tête que ce menu a pour cible principale l'ensemble des personnes qui pour diverses raisons, ont des difficultées à avoir une vue d'ensemble claire, ou à naviguer simplement dans un contenu conséquent.

*(Je suis à même de proposer une PR sur ce point, mais pas avant vendredi 13 ou samedi 14)*

**Comment by dunglas** [comment]
Oui très bonne idée. Le site a été fait à l’arrache lundi, donc les PR de ce type sont vraiment les bienvenues !

**Comment by Gregcop1** [comment]
Merci
