### ISSUE TITLE
Style du site

### ISSUE THREAD

**Issue by Gregcop1** [onestlatech/onestlatech.github.io#968]
Je travaille actuellement sur un design un peu moins austère du site. Sans partir dans le grandiloquent non plus. L'idée :
- un minimum de CSS
- un découpage en rubrique (Appel, Publication, A propos). On pourra en ajouter par la suite (peut-être revue de presse, etc.). La rubrique "publication" s'affichera à partir du moment où on aura un article dans le dossier "/posts"
- poser les bases d'une charte graphique (c'est pas une histoire de goût mais juste d'avoir un truc à peu près cohérent partout)

**Comment by pierreroth64** [comment]
🤔 ... _"à partir du moment où on aura un article dans le dossier /posts"_ J'ai signé l'appel car je suis en phase totale avec le texte. Par contre, serais-je en phase avec des posts ultérieurs ? Pas certain. Du coup, je retire ma signature ? ...
Je pense qu'on peut bien entendu jouer sur le style (quoiqu'un site minimaliste, low-tech me plaise bien) mais ne **surtout pas** changer / ajouter du contenu... Ce n'est qu'un avis bien entendu mais j'ai bien aimé [ce commentaire](https://github.com/onestlatech/onestlatech.github.io/pull/135#issuecomment-563482368) de @dunglas Bravo pour le boulot en tout cas.
